name: Publish

on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegando o ultimo codigo
        uses: actions/checkout@v2

      - name: 👷 Preparando o Node
        uses: actions/setup-node@v2
        with:
          node-version: '17.4.0'

      - name: 🔨 Construindo...
        run: |
          npm install
          npm run postinstall

      - name: 📂 Sincronizando os arquivos
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER_IP }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/desafio-front/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/cypress/**
